/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.VendorAdminRole;

import business.Enterprise.VendorStoreEnterprise;
import business.Product.Product;
import com.onbarcode.barcode.Code39;
import com.onbarcode.barcode.IBarcode;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.awt.Label;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Juilee
 */
public class AddProductJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private VendorStoreEnterprise enterprise;

    /**
     * Creates new form AddProductJPanel
     */
    public AddProductJPanel(JPanel userProcessContainer, VendorStoreEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProdName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAvail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Add Product");

        jLabel2.setText("Name");

        jLabel3.setText("Price");

        jLabel4.setText("Availability");

        jLabel5.setText("Type");

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select", "Apparel", "Automotive", "Baby", "Beauty", "Books", "Cell Phones and Accessories", "Electronics", "Gourmet", "Grocery", "Health and Personal Care", "Home and Garden", "Home Improvement", "Industrial and Scientific", "Jewelry", "Magazines and Newspapers", "Music ", "Musical Instruments", "Office Products", "Pet Supplies", "Shoes", "Software", "Sporting Goods", "Toys and Games", "Video/DVD", "Video Games", "Watches", " " }));

        submitJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkok.png"))); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_icon.gif"))); // NOI18N
        backJButton.setText(" Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProdName)
                                    .addComponent(txtPrice)
                                    .addComponent(txtAvail)
                                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(submitJButton)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitJButton)
                    .addComponent(backJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
public Code39 barcodeDisplay(String str) {
        Code39 barcode = new Code39();
        barcode.setData(str);
        barcode.setExtension(false);
        barcode.setAddCheckSum(true);
        barcode.setN(3.0f);
        barcode.setI(1.0f);
        barcode.setShowStartStopInText(true);
        barcode.setUom(IBarcode.UOM_PIXEL);
        barcode.setX(1f);
        barcode.setY(75f);
        barcode.setLeftMargin(0f);
        barcode.setRightMargin(0f);
        barcode.setTopMargin(0f);
        barcode.setBottomMargin(0f);
        barcode.setResolution(72);
        barcode.setShowText(true);
        barcode.setTextFont(new Font("Arial", 0, 12));
        barcode.setTextMargin(6);
        return barcode;
    }
    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        try {

            if (!typeCombo.getSelectedItem().toString().equalsIgnoreCase("--Select")) {
                Product p = enterprise.getProductCatalog().addProduct();
                p.setProdName(txtProdName.getText().trim());
                p.setAvailability(Integer.parseInt(txtAvail.getText().trim()));
                p.setPrice(Float.parseFloat(txtPrice.getText().trim()));
                p.setProductType(typeCombo.getSelectedItem().toString());
                Code39 barcode = new Code39();

                barcode.setData(p.getBarcode());

                barcode.setExtension(false);

                barcode.setAddCheckSum(true);
                barcode.setN(3.0f);
	// The space between 2 characters in code 39; This a multiple of X; The default is 1.;
                // Valid value is from 1.0 (inclusive) to 5.3 (exclusive)
                barcode.setI(1.0f);
                barcode.setShowStartStopInText(true);

                // Code 39 Unit of Measure, pixel, cm, or inch
                barcode.setUom(IBarcode.UOM_PIXEL);
                // Code 39 barcode bar module width (X) in pixel
                barcode.setX(1f);
                // Code 39 barcode bar module height (Y) in pixel
                barcode.setY(75f);

                // Code 39 image margins
                barcode.setLeftMargin(0f);
                barcode.setRightMargin(0f);
                barcode.setTopMargin(0f);
                barcode.setBottomMargin(0f);

                // barcode image resolution in dpi
                barcode.setResolution(72);

                // disply barcode encoding data below the barcode
                barcode.setShowText(true);
                // barcode encoding data font style
                barcode.setTextFont(new Font("Arial", 0, 12));
                // space between barcode and barcode encoding data
                barcode.setTextMargin(6);

                //  barcode displaying angle
                barcode.setRotate(IBarcode.ROTATE_0);
                ImageIcon img = new ImageIcon(barcode.drawBarcode());
                

//                   Label barcodeLabel= new Label(img);
//                   jLabel1.setIcon(img);
                JOptionPane.showMessageDialog(this, "Please approve product- " + p.getProdName(), "RFID Scanner", JOptionPane.WARNING_MESSAGE);
                int dialogResult = JOptionPane.showConfirmDialog(this, img, "Scan this Barcode", JOptionPane.YES_NO_OPTION);

                if (dialogResult == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(this, "Product- " + p.getProdName()+ "added successfully","Success Message", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(this, "Attempt unsuccessful", "Error Message", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a product type", "Error Message", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Attempt unsuccessful", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageProducts panel = (ManageProducts) component;
        panel.populate();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField txtAvail;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JComboBox typeCombo;
    // End of variables declaration//GEN-END:variables
}
