/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SystemAdminRole;

import business.EcommerceEcoSystem;
import business.Network.Network;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juilee
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcommerceEcoSystem system;

    /**
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworkJPanel(JPanel userProcessContainer, EcommerceEcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateStateComboBox();
        AddLocationPanel.setVisible(false);
    }

    public void populateStateComboBox() {
        stateViewCombobox.removeAllItems();

//        stateViewCombobox.addItem("--Select");
        stateSelectCombobox.removeAllItems();
//        stateSelectCombobox.addItem("--Select");

        for (Network n : system.getNetworkDirectory().getNetworkList()) {
            stateViewCombobox.addItem(n);
            stateSelectCombobox.addItem(n);
        }
//        stateViewCombobox.setSelectedItem("--Select");
//        stateSelectCombobox.setSelectedItem("--Select");
    }

    public void populateLocationTable(Network n) {

        DefaultTableModel model = (DefaultTableModel) networkJTable.getModel();

        model.setRowCount(0);
        for (Network city : n.getCityList()) {
            Object[] row = new Object[2];
            row[0] = city.toString(city);
            row[1] = city.getZipCode();
            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stateViewCombobox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        networkJTable = new javax.swing.JTable();
        AddLocationPanel = new javax.swing.JPanel();
        stateSelectCombobox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCityName = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSubmitPanel = new javax.swing.JButton();
        btnCancelPanel = new javax.swing.JButton();
        btnAddLocation = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnDeleteLocation = new javax.swing.JButton();

        jLabel1.setText("Manage Networks");

        jLabel2.setText("Select State");

        stateViewCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stateViewCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateViewComboboxActionPerformed(evt);
            }
        });

        networkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City name", "Zipcode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(networkJTable);

        stateSelectCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Select State");

        jLabel4.setText("City name");

        txtCityName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCityNameKeyPressed(evt);
            }
        });

        jLabel5.setText("Zipcode");

        btnSubmitPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkok.png"))); // NOI18N
        btnSubmitPanel.setText("Submit");
        btnSubmitPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPanelActionPerformed(evt);
            }
        });

        btnCancelPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Action-cancel-icon.png"))); // NOI18N
        btnCancelPanel.setText("Cancel");
        btnCancelPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddLocationPanelLayout = new javax.swing.GroupLayout(AddLocationPanel);
        AddLocationPanel.setLayout(AddLocationPanelLayout);
        AddLocationPanelLayout.setHorizontalGroup(
            AddLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLocationPanelLayout.createSequentialGroup()
                .addGroup(AddLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLocationPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(AddLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(47, 47, 47)
                        .addGroup(AddLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtZipCode)
                            .addComponent(stateSelectCombobox, 0, 199, Short.MAX_VALUE)
                            .addComponent(txtCityName)))
                    .addGroup(AddLocationPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnSubmitPanel)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelPanel)))
                .addContainerGap())
        );
        AddLocationPanelLayout.setVerticalGroup(
            AddLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(stateSelectCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(AddLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitPanel)
                    .addComponent(btnCancelPanel))
                .addContainerGap())
        );

        btnAddLocation.setText("Add new Store Location");
        btnAddLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLocationActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_icon.gif"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDeleteLocation.setText("Delete Location");
        btnDeleteLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(stateViewCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAddLocation)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDeleteLocation))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AddLocationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(stateViewCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLocation)
                    .addComponent(btnDeleteLocation))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(AddLocationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLocationActionPerformed
        AddLocationPanel.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btnAddLocationActionPerformed

    private void btnSubmitPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPanelActionPerformed
        try {
            if (stateSelectCombobox.getSelectedItem().equals("--Select")) {
                JOptionPane.showMessageDialog(this, "Error Message", "Please select a state", JOptionPane.ERROR_MESSAGE);
            } else {
                Network n = (Network) stateSelectCombobox.getSelectedItem();
                Network city = n.addCity(n);
                city.setCityName(txtCityName.getText());
                city.setZipCode(Integer.parseInt(txtZipCode.getText()));
                populateLocationTable(n);
                stateViewCombobox.setSelectedItem(n);
                JOptionPane.showMessageDialog(this, "Location- " + city.getCityName() + " added successfully", "Success Message", JOptionPane.INFORMATION_MESSAGE);
                txtCityName.setText("");stateSelectCombobox.setSelectedIndex(0);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Attempt unsuccessful", "Error Message",  JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitPanelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stateViewComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateViewComboboxActionPerformed
//     if(stateViewCombobox.getSelectedItem().equals("--Select"))
//            {
//                JOptionPane.showMessageDialog(this,"Error Message","Please select a state", JOptionPane.ERROR_MESSAGE);
//            }
//     else 
//            {
        Network n = (Network) stateViewCombobox.getSelectedItem();
        if (n != null) {
            populateLocationTable(n);
        }
//            }
//                else if(n.equals("--Select"))
//                {
//                    
//                }

//            }
// TODO add your handling code here:
    }//GEN-LAST:event_stateViewComboboxActionPerformed

    private void btnCancelPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPanelActionPerformed
        AddLocationPanel.setVisible(false);
        txtCityName.setText("");
        stateSelectCombobox.setSelectedIndex(0);
        stateViewCombobox.setSelectedIndex(0);
        txtZipCode.setText("");
        Network n=(Network)stateViewCombobox.getSelectedItem();
        if(n!=null)
        {
            populateLocationTable(n);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelPanelActionPerformed

    private void txtCityNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityNameKeyPressed

    private void btnDeleteLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLocationActionPerformed
        int selectedRow= networkJTable.getSelectedRow();
if(selectedRow>=0)
{
int dialogButton = JOptionPane.YES_NO_OPTION;
int dialogResult= JOptionPane.showConfirmDialog(null,"Would you like to delete this network?","Warning",dialogButton);
if(dialogResult==JOptionPane.YES_OPTION)
{
Network network =(Network)stateViewCombobox.getSelectedItem();
String cityName = networkJTable.getValueAt(selectedRow,0).toString();
int zipCode = Integer.parseInt(networkJTable.getValueAt(selectedRow,1).toString());
Network city = network.getCityObjectFromName(cityName, network, zipCode);
network.removeCity(network, city);
    populateLocationTable(network);
//resetField()
}
}else
{
JOptionPane.showMessageDialog(null,"Please select a row first");
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteLocationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddLocationPanel;
    private javax.swing.JButton btnAddLocation;
    private javax.swing.JButton btnCancelPanel;
    private javax.swing.JButton btnDeleteLocation;
    private javax.swing.JButton btnSubmitPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable networkJTable;
    private javax.swing.JComboBox stateSelectCombobox;
    private javax.swing.JComboBox stateViewCombobox;
    private javax.swing.JTextField txtCityName;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
