/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SystemAdminRole;

import business.EcommerceEcoSystem;
import business.Enterprise.CustomerEnterprise;
import business.Enterprise.Enterprise;
import business.Network.Network;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juilee
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcommerceEcoSystem system;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel(JPanel userProcessContainer, EcommerceEcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        populateComboBox();
        populateEnterprise();
    }

    private void populateEnterprise() {
        enterpriseComboBox.removeAllItems();
        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {

            enterpriseComboBox.addItem(type);

        }
    }

    public void populateComboBox() {
        stateViewCombobox.removeAllItems();
        cityComboBox.removeAllItems();
        zipCodeComboBox.removeAllItems();
        for (Network n : system.getNetworkDirectory().getNetworkList()) {
            stateViewCombobox.addItem(n);

        }

    }

    public void populateCityCombobox(Network n) {
        cityComboBox.removeAllItems();
        if (n != null) {
            for (Network city : n.getCityList()) {

                cityComboBox.addItem(city.getCityName());
            }
        }

    }

    public void populateTable(String cityName, int zip, Network state) {

        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        Network city = state.getCityObjectFromName(cityName, state, zip);
        for (Enterprise enterprise : city.getEnterpriseDirectory().getEnterpriseList()) {
            Object[] row = new Object[3];
            row[0] = enterprise;
            row[1] = city.getCityName();
            row[2] = city.getZipCode();
            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stateViewCombobox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cityComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        enterpriseComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        btnSubmitPanel = new javax.swing.JButton();
        btnCancelPanel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        zipCodeComboBox = new javax.swing.JComboBox();

        jLabel1.setText("Manage Enterprise");

        jLabel2.setText("Select State");

        stateViewCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stateViewCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateViewComboboxActionPerformed(evt);
            }
        });

        jLabel3.setText("Select City");

        cityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Enterprise Type");

        enterpriseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "City Name", "Zipcode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);

        btnSubmitPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkok.png"))); // NOI18N
        btnSubmitPanel.setText("Submit");
        btnSubmitPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPanelActionPerformed(evt);
            }
        });

        btnCancelPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Action-cancel-icon.png"))); // NOI18N
        btnCancelPanel.setText("Cancel");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_icon.gif"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juilee\\Desktop\\Project images\\MB-ClassifiedAds-admin-small-icon.png")); // NOI18N
        jButton2.setText("Add Enterprise Admin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Enterprise Name");

        jLabel6.setText("Select Zipcode");

        zipCodeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        zipCodeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSubmitPanel)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelPanel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(enterpriseComboBox, 0, 199, Short.MAX_VALUE)
                                            .addComponent(txtEnterpriseName)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stateViewCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(zipCodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(stateViewCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(zipCodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(enterpriseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitPanel)
                    .addComponent(btnCancelPanel)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stateViewComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateViewComboboxActionPerformed
        Network n = (Network) stateViewCombobox.getSelectedItem();
        populateCityCombobox(n); // TODO add your handling code here:
    }//GEN-LAST:event_stateViewComboboxActionPerformed

    private void btnSubmitPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPanelActionPerformed

        try {
            Network state = (Network) stateViewCombobox.getSelectedItem();
            String cityName = cityComboBox.getSelectedItem().toString();
            int zipcode = Integer.parseInt(zipCodeComboBox.getSelectedItem().toString());
            Network city = state.getCityObjectFromName(cityName, state, zipcode);
            Enterprise e;
            if (enterpriseComboBox.getSelectedItem().equals(Enterprise.EnterpriseType.CustomerEnterprise.CustomerEnterprise)) {
                for (Enterprise enterprise : city.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof CustomerEnterprise) {
                        JOptionPane.showMessageDialog(this, "Customer Enterprise already exists", "Error Message", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                }
                e = city.getEnterpriseDirectory().createEnterprise(Enterprise.EnterpriseType.CustomerEnterprise.CustomerEnterprise);
            } else {
                e = city.getEnterpriseDirectory().createEnterprise(Enterprise.EnterpriseType.VendorStore.VendorStore);
            }
            e.setName(txtEnterpriseName.getText());
            JOptionPane.showMessageDialog(this, txtEnterpriseName.getText() + " added successfully", "Success Message", JOptionPane.INFORMATION_MESSAGE);
            populateTable(cityName, zipcode, state);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Attempt unsuccessful", "Error Message", JOptionPane.ERROR_MESSAGE);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitPanelActionPerformed
    public void populateZip(String cityname, Network n) {
        zipCodeComboBox.removeAllItems();

        ArrayList<Integer> ziplist = n.getZipCodeList(cityname, n);

        for (int i : ziplist) {
            if (i != 0) {
                zipCodeComboBox.addItem(i);
            }
        }
    }
    private void cityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityComboBoxActionPerformed
        if (cityComboBox.getSelectedItem() != null) {
            String cityname = (String) cityComboBox.getSelectedItem();
            Network n = (Network) stateViewCombobox.getSelectedItem();
            populateZip(cityname, n);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_cityComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void zipCodeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeComboBoxActionPerformed
       // populateTable(cityComboBox.getSelectedItem().toString(),Integer.parseInt(zipCodeComboBox.getSelectedItem().toString()),(Network)stateViewCombobox.getSelectedItem());  // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeComboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = enterpriseJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an enterprise", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        Enterprise enterprise = (Enterprise) enterpriseJTable.getValueAt(selectedRow, 0);
        ManageEnterpriseAdminJPanel panel = new ManageEnterpriseAdminJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageEnterpriseAdminJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelPanel;
    private javax.swing.JButton btnSubmitPanel;
    private javax.swing.JComboBox cityComboBox;
    private javax.swing.JComboBox enterpriseComboBox;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.List list1;
    private javax.swing.JComboBox stateViewCombobox;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JComboBox zipCodeComboBox;
    // End of variables declaration//GEN-END:variables
}
