/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CustomerAdminRole;

import business.EcommerceEcoSystem;
import business.Enterprise.CustomerEnterprise;
import business.db4OUtil.DB4OUtil;
import java.awt.CardLayout;
import static java.time.Clock.system;
import javax.swing.JPanel;
import userInterface.SystemAdminRole.ManageNetworkJPanel;

/**
 *
 * @author Juilee
 */
public class CustomerAdminWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private CustomerEnterprise enterprise;
    private EcommerceEcoSystem system;
    private DB4OUtil dB4OUtil;
    /**
     * Creates new form CustomerAdminWorkAreaJPanel
     */
    public CustomerAdminWorkAreaJPanel(JPanel userProcessContainer,CustomerEnterprise enterprise) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.enterprise=enterprise;
        this.dB4OUtil=DB4OUtil.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnManageOrg = new javax.swing.JButton();

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/login-icon.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnManageOrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Small-arrow-right-fast-forward-icon.png"))); // NOI18N
        btnManageOrg.setText("Manage Organization");
        btnManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnManageOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnManageOrg)
                .addGap(40, 40, 40)
                .addComponent(btnLogout)
                .addGap(122, 122, 122))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        system=EcommerceEcoSystem.getInstanceOf();
        dB4OUtil.storeSystem(system);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrgActionPerformed
        ManageCustomerOrgJPanel panel = new ManageCustomerOrgJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageCustomerOrgJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageOrg;
    // End of variables declaration//GEN-END:variables
}
